graph TD
    start --> main
    main --> setvbuf
    main --> printf
    main --> fgets
    main --> c
    c --> strtok
    c --> strcmp
    c --> atoi
    c --> e
    c --> a
    c --> h
    e --> strcpy
    e --> strncpy
    e --> snprintf
    e --> puts
    a --> strcmp
    a --> printf
    h --> time
    h --> localtime
    h-->puts
    h-->getpid
    h-->snprintf
    h-->open
    h-->write
    h-->open
    i-->time
    i-->puts
    j-->getenv
    j-->strstr
    j-->setuid
    j-->puts
    k-->open
    k-->printf
    k-->read
    k-->close
    l-->printf
    m-->fopen
    m-->fgets
    m-->printf
    m-->fclose
